### ISSUE TITLE
Ensure XML output from xdoc generator

### ISSUE THREAD

**Issue by rfscholte** [codehaus-plexus/modello#13]
With Java8 the javadoc is expected to be HTML4, which implies usage of unbalanced tags for linebreaks (`<br>`), horizontal row (`<hr>`), etc. In case of Xdoc these should be transformed to valid XML.

**Comment by michael-o** [comment]
You mean HTML5, don't you?

**Comment by rfscholte** [comment]
No, Javadoc8 means HTML4, http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html
Which also means that some attributes/tags are not supported :(

**Comment by michael-o** [comment]
Thanks for the clarification, there has been a lot of fuzz round doclint in Javadoc.
