### ISSUE TITLE
Required fields lead to non required element in XSD

### ISSUE THREAD

**Issue by kwin** [codehaus-plexus/modello#162]
E.g. the required field `prefix` from https://github.com/apache/maven/blob/master/maven-repository-metadata/src/main/mdo/metadata.mdo#L354-L360 leads to this XSD:
```
<xs:element minOccurs="0" name="prefix" type="xs:string">
```

Obsviously the element with name `prefix` must leave out minOccurs="0" to be required in the XMLs.

**Comment by michael-o** [comment]
Please link the spot in question. I have provided it in the JIRA issue.

**Comment by kwin** [comment]
This seems to be caused by https://github.com/codehaus-plexus/modello/blob/8467ab87f95557c8c6409f5ebe613caf240836b3/modello-plugins/modello-plugin-xsd/src/main/java/org/codehaus/modello/plugin/xsd/XsdGenerator.java#L245-L247.

**Comment by kwin** [comment]
The reason for this behaviour seems to be driven by pom.xml specifics, i.e. POMs are merged with their parents before they need to be valid. As this is definitely an edge case Modello should have a flag for enabling/disabling that behaviour. 
By default it is reasonable to assume that the XML is not requiring post-processing before validating it against the schema.

**Comment by michael-o** [comment]
> The reason for this behaviour seems to be driven by pom.xml specifics, i.e. POMs are merged with their parents before they need to be valid. As this is definitely an edge case Modello should have a flag for enabling/disabling that behaviour. By default it is reasonable to assume that the XML is not requiring post-processing before validating it against the schema.

I fully agree with that.
