### ISSUE TITLE
Importing external classes

### ISSUE THREAD

**Issue by mkarg** [codehaus-plexus/modello#23]
Currently a model must be self-contained, i. e. a field must have a type which itself is described as a class of the model, or it must be a *primitive* Java type.

In reality there is often the need to model fields having a type external to the model but not being a *primitive* type. For example, a model shall contain a field referencing a plexus `FileMapper`. Currently modello will fail because that class is unknown to modello, while it actually is known to the class-path.

To make modello more useful, I'd like to propose a syntax extension which allows to declare imports. Such an import declaration would effectively allow to use any class as a type in the model, without the need to add it to the model itself as a class, and without effectively creating any code for it other than an "imports" declaration for java code output.

**Comment by mykelalvis** [comment]
:+1:
