### ISSUE TITLE
`xpp3-extended-writer` produces erroneous class name (`null` rather than `Ex`)

### ISSUE THREAD

**Issue by mykelalvis** [codehaus-plexus/modello#260]
When location tracking is active, [`Xpp3WriterGenerator#initialize`](https://github.com/codehaus-plexus/modello/blob/modello-2.0.0/modello-plugins/modello-plugin-xpp3/src/main/java/org/codehaus/modello/plugin/xpp3/Xpp3WriterGenerator.java#L77-L81)  forces the variable `extendedClassnameSuffix` to be set to the `ModelloParameterConstants.EXTENDED_CLASSNAME_SUFFIX` property that was passed into the `#initialize` call higher in the call hierarchy.

`EXTENDED_CLASSNAME_SUFFIX` apparently _does_ get set in the [`ModelloXpp3ExtendedWriterMojo#customizeParameters`](https://github.com/codehaus-plexus/modello/blob/modello-2.0.0/modello-maven-plugin/src/main/java/org/codehaus/modello/maven/ModelloXpp3ExtendedWriterMojo.java#L55-L63) but apparently _does not get set_  at any point in the `generate` MOJO's call. This causes `generate` executions using `xpp3-extended-writer` to use the value `null` for `extendedClassnameSuffix` resulting in a generated `marshallerName` of  `XXXXXXpp3Writernull` rather than `XXXXXXXpp3WriterEx`.

The `xpp3-extended-reader` uses a different method to calculate the extension value, and thus does not suffer from this bug.

**Comment by kwin** [comment]
@mykelalvis Thanks for the report, can you come up with a test case for this and in the best case also a fix as PR?

**Comment by mykelalvis** [comment]
Due to a version override, I was probably using a _much_ [older version](https://github.com/codehaus-plexus/modello/blob/modello-1.11/modello-plugins/modello-plugin-xpp3/src/main/java/org/codehaus/modello/plugin/xpp3/Xpp3WriterGenerator.java#L80) of modello within the codebase that used this.

This has been reworked in 2.x+, so I'm closing this.
