### ISSUE TITLE
Provide a way to plug in optimizations when reading xpp3

### ISSUE THREAD

**Issue by gnodet** [codehaus-plexus/modello#33]
The main idea would be to allow a more advanced `ContentTransformer` so that maven model reader would record the exact locations that require interpolation, avoiding the need to scan the whole model.
On very large projects, the interpolation is roughly half the time needed to read the projects (which is 50s in my case when reading camel with maven 3.6.1).

@hboutemy @olamy any early feedback on the above ?

**Comment by gnodet** [comment]
What I have in mind is to convey more informations while parsing so that the `ContentTransformer` would be given some kind of ognl path to the value, so instead of `groupId`, it would be given `model.dependencies[2].groupId`.
The idea is that maven would use a custom `ContentTransformer` that will record strings to be interpolated (those containing `${`) along with the path.  This list would then be used to directly perform the needed interpolation instead of going through the whole tree.

**Comment by gnodet** [comment]
I'm mostly done with the modello part, that was the easy one though.
On the maven side, the difficulties come when merging stuff, but it looks doable.

**Comment by rfscholte** [comment]
What's the status? I don't see any code

**Comment by gnodet** [comment]
I've just pushed the changes I had on my local repo.  I don't recall the exact state though...
https://github.com/gnodet/modello/commit/3ac058fb57f9c6275d94d44e5ded668080000cf1

**Comment by gnodet** [comment]
@rfscholte I also have some changes to maven I can push, but again, I'm not sure what the status is.  The overall goal was to speed up the interpolation, because for large projects, it can be very time consuming when building the actual model.
I think at the end, I choose to use a non reflection based interpolator instead as part of https://github.com/apache/maven/pull/259, so I'm not sure this particular issue is still relevant.

**Comment by rfscholte** [comment]
We've switch to https://maven.apache.org/ref/3.6.3/maven-model-builder/apidocs/org/apache/maven/model/interpolation/StringVisitorModelInterpolator.html which should indeed speed up interpolation.
Should we close this ticket or have another look at it?

**Comment by gnodet** [comment]
@rfscholte yeah, my PRs for maven 3.6.3 did bring a lof of speed improvements.
I'll try to look if there's still room for another set of improvements with the `ContentTransformer`.

**Comment by gnodet** [comment]
Closing, as I could not find a way to actual leverage that correctly in maven and found other ways to optimize the model loading (mainly using the `StringVisitorModelInterpolator`).
