### ISSUE TITLE
modello-maven-plugin doesn't work with plexus-xml 4.x anymore

### ISSUE THREAD

**Issue by alitokmen** [codehaus-plexus/modello#346]
The modello-maven-plugin doesn't work with plexus-xml 4.x anymore, we get errors such as:

```
constructor MXParser in class org.codehaus.plexus.util.xml.pull.MXParser cannot be applied to given types;
  required: no arguments
  found: org.codehaus.plexus.util.xml.pull.EntityReplacementMap
  reason: actual and formal argument lists differ in length
```

Are there adaptations of the modello-maven-plugin planned for plexus-xml 4.x?

**Comment by gnodet** [comment]
Could you share something to reproduce the problem ? The code in plexus-xml 4.x is supposed to be fully compatible with plexus-utils 3.x.  In particular, this constructor is [still present in the code](https://github.com/codehaus-plexus/plexus-xml/blob/master/src/main/java/org/codehaus/plexus/util/xml/pull/MXParser.java#L463-L465).

**Comment by alitokmen** [comment]
Hi @gnodet thanks for your reply.

I do not have an "isolated" example, the Maven build is for https://github.com/codehaus-cargo/cargo/tree/76d2a5267cb00c1393cef93ed0161a831f39543e/extensions/maven3/plugin and the build logs can be found on https://semaphoreci.com/codehaus-cargo/cargo/branches/dependabot-maven-org-codehaus-plexus-plexus-utils-4-0-0/builds/4

Does this help at all?

**Comment by alitokmen** [comment]
Hi everyone

After some pain, I found why: our build happens to have `org.apache.maven:maven-artifact` as a dependency, which in turn has a very old version of Plexus utils (2.x) as a subdependency.

As a result, the fix is simple: though we "only" need `plexus-xml`, we also keep `plexus-utils` (of course, with the latest version 4.x) as a dependency, so that the very old `plexus-utils` from `maven-artifact` is "eclipsed out".

Regards
