### ISSUE TITLE
 Modello Java Plugin tests appear broken at head

### ISSUE THREAD

**Issue by elharo** [codehaus-plexus/modello#35]
INFO] --- maven-dependency-plugin:2.1:copy-dependencies (copy-test-libs) @ modello-plugin-java ---
[INFO] Copying classes to /home/elharo/modello/modello-plugins/modello-plugin-java/target/test-libs/modello-core.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Modello 1.12-SNAPSHOT:
[INFO] 
[INFO] Modello ............................................ SUCCESS [  0.035 s]
[INFO] Modello Core ....................................... SUCCESS [  1.824 s]
[INFO] Modello Test Package ............................... SUCCESS [  0.094 s]
[INFO] Modello Plugins .................................... SUCCESS [  0.003 s]
[INFO] Modello Java Plugin ................................ FAILURE [  0.275 s]
[INFO] Modello XML Plugin ................................. SKIPPED
[INFO] Modello StAX Plugin ................................ SKIPPED
[INFO] Modello Model Version Converter Plugin ............. SKIPPED
[INFO] Modello Dom4J Plugin ............................... SKIPPED
[INFO] Modello Jackson Plugin ............................. SKIPPED
[INFO] Modello JDOM Plugin ................................ SKIPPED
[INFO] Modello JSON-Schema Plugin ......................... SKIPPED
[INFO] Modello SAX Plugin ................................. SKIPPED
[INFO] Modello SnakeYaml Plugin ........................... SKIPPED
[INFO] Modello XSD Plugin ................................. SKIPPED
[INFO] Modello XDOC Plugin ................................ SKIPPED
[INFO] Modello XPP3 Plugin ................................ SKIPPED
[INFO] Modello Maven Plugin ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.364 s
[INFO] Finished at: 2020-02-17T08:35:05-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.1:copy-dependencies (copy-test-libs) on project modello-plugin-java: Error copying artifact from /home/elharo/modello/modello-core/target/classes to /home/elharo/modello/modello-plugins/modello-plugin-java/target/test-libs/modello-core.jar: /home/elharo/modello/modello-core/target/classes (Is a directory) -> [Help 1]
[ERROR]

**Comment by michael-o** [comment]
Works for me on:

```
mosipov@mika-ion ~/Projekte/modello]$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/share/java/maven
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /usr/local/openjdk8/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "freebsd", version: "11.3-release-p6", arch: "i386", family: "unix"
```

and

```
PS D:\Entwicklung\Projekte\modello-2> mvn -v
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: D:\Entwicklung\Programme\apache-maven-3.5.4\bin\..
Java version: 1.8.0_232, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-8.0.232.09-hotspot\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by pzygielo** [comment]
@elharo I think you need to request at least phase `package`, as `test` of earlier module does not prepare/attach jar required in dependant.

**Comment by elharo** [comment]
OK. `mvn verify` works. Not totally sure why mvn test doesn't, but I can work with this. Thanks

**Comment by pzygielo** [comment]
@elharo So this could be closed, couldn't it?
