### ISSUE TITLE
Modello Java Mojo is marked as threadsafe, but is not

### ISSUE THREAD

**Issue by cstamas** [codehaus-plexus/modello#366]
The Modello Java Mojo (did not check others) is marked as threadsafe, but is not.

Proof: try to build maven-3.9.x branch with any of these: `-T` (either plain or smart builder) or mvnd, and Modello fails badly. Code generator is stateful singleton, and generated sources are not landing on desired place...

**Comment by gnodet** [comment]
Superseded by #415

**Comment by cstamas** [comment]
This issue is not solved by 2.2.0, tested locally. While the generators are made prototypes (non singletons), the 3 core components (managers) are still singletons, and the fact they inject `Map<String, Generator>` still makes generators singletons... 

My test build with 2.2.0 still fails. My test build passes if I make non-singletons these:
* DefaultGeneratorPluginManager
* DefaultMetadataPluginManager
