### ISSUE TITLE
Recursive association

### ISSUE THREAD

**Issue by emetsger** [codehaus-plexus/modello#4]
I'm unable to create a Modello model that has a recursive association.  I'd like to be able to generate the following Java class:

```
class RecursionNode {
  RecursionNode parent;
  // getters, setters, etc.
}
```

In my model I define this using an `association`, where the `type` is the class being generated by Modello:

```
<association>
  <type>com.github.jasminb.jsonapi.models.recursion.RecursionNode</type>
</association>
```

When I attempt to generate the model, I receive:

> org.apache.maven.plugin.MojoExecutionException: Error generating: There is no class 'com.github.jasminb.jsonapi.models.recursion.RecursionNode' in the version range '0.0.0+'.
> at org.codehaus.modello.maven.AbstractModelloGeneratorMojo.doExecute(AbstractModelloGeneratorMojo.java:289)
> at org.codehaus.modello.maven.AbstractModelloGeneratorMojo.execute(AbstractModelloGeneratorMojo.java:190)
> at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
> at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
> at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
> at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
> at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
> at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
> at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:497)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
> at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
> at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
> at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.codehaus.modello.ModelloRuntimeException: There is no class 'com.github.jasminb.jsonapi.models.recursion.RecursionNode' in the version range '0.0.0+'.
> at org.codehaus.modello.model.Model.getClass(Model.java:192)
> at org.codehaus.modello.model.ModelAssociation.validateElement(ModelAssociation.java:138)
> at org.codehaus.modello.model.BaseElement.validate(BaseElement.java:179)
> at org.codehaus.modello.core.DefaultModelloCore.validate(DefaultModelloCore.java:334)
> at org.codehaus.modello.core.DefaultModelloCore.loadModel(DefaultModelloCore.java:185)
> at org.codehaus.modello.core.DefaultModelloCore.loadModel(DefaultModelloCore.java:85)
> at org.codehaus.modello.maven.AbstractModelloGeneratorMojo.doExecute(AbstractModelloGeneratorMojo.java:226)
> ... 23 more

Is it possible to work around this validation in some way?

**Comment by rfscholte** [comment]
This should work:

    <classes>
      <class rootElement="true">
        <name>RecursionNode</name>
        <version>0.0.0+</version>
        <fields>
          <field>
            <name>parent</name>
            <association>
              <multiplicity>1</multiplicity>
              <type>RecursionNode</type>
            </association>
          </field>
          <field>
            <name>children</name>
            <type>List</type>
            <association>
              <type>RecursionNode</type>
              <multiplicity>*</multiplicity>
            </association>
          </field>
        </fields>
      </class>
    </classes>

Unittest added to verify
