### ISSUE TITLE
Publish model XSDs

### ISSUE THREAD

**Issue by cstamas** [codehaus-plexus/modello#469]

**Comment by slawekjaranowski** [comment]
We have:
https://codehaus-plexus.github.io/modello/xsd/modello-2.0.0.xsd

**Comment by cstamas** [comment]
Right, and model version is still 2.0.0, I missed that:

https://github.com/codehaus-plexus/modello/blob/1bf9f4567f9da9e7e917f07f6468a55d22f41ff4/pom.xml#L459
