### ISSUE TITLE
Usage of travis-ci.org

### ISSUE THREAD

**Issue by pzygielo** [codehaus-plexus/modello#55]
It seems that travis is not reporting back to github for this project.
However - it continues to [fire builds](https://travis-ci.org/github/codehaus-plexus/modello/builds) (and consume resources which one could think were replaced by github actions).

Please consider some changes, for example:
- fix always failing build - as there is no longer JDK7 available on travis and make travis give feedback to github for configurations not covered by github actions
- stop using travis for this project

**Comment by olamy** [comment]
travis file removed
