### ISSUE TITLE
Support namespaces

### ISSUE THREAD

**Issue by rhuss** [codehaus-plexus/modello#6]
As pointed out in https://issues.apache.org/jira/browse/MNG-6036 it would be cool if modello would support parsing namespaces, even when it completely ignore it afterwards.

In a first step, it would be sufficient if modello would completely ignore namespace prefixes by stripping them off.

**Comment by elharo** [comment]
Very tentativey what I think needs to happen is that ModelReader.loadModel needs to stop using the built-in XmlPullParser and instead use a parser that respects namespaces.
