### ISSUE TITLE
Dead Link to Modello Wiki

### ISSUE THREAD

**Issue by wiverson** [codehaus-plexus/modello#81]
https://codehaus-plexus.github.io/modello/modello-maven-plugin/faq.html

...has a link to an old Codehaus wiki that is no longer available.

http://docs.codehaus.org/display/MODELLO/Home

There is a little bit of documentation from the old wiki still up on Wayback Machine, not sure if any of it still matters.

http://web.archive.org/web/20150504031633if_/http://docs.codehaus.org/display/MODELLO/Home
http://web.archive.org/web/20150509112511if_/http://docs.codehaus.org/display/MODELLO/MODELLO-228+convergence+between+Modello+and+EMF

My two cents: the tiny bit of stuff from the old two wiki pages can just be copy/pasted into the FAQ section and call it good.

**Comment by rfscholte** [comment]
Let's simply remove that link, all required information should be available at https://codehaus-plexus.github.io/modello/

**Comment by michael-o** [comment]
Skim the FAQ with a PR.

**Comment by slachiewicz** [comment]
Fixed with 8fe55aba46a3e5590eaf83cc89121148d3906a2b
